{{- if .Values.namespaces.backend.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.backend.name }}
---
{{- end }}

{{- if .Values.namespaces.stacks.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.stacks.name }}
---
{{- end }}
