{{- if .Values.fluentbit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentbit.serviceAccount.name }}
  namespace: {{ .Values.fluentbit.namespace | default .Values.namespaces.logging.name }}
  {{- if .Values.fluentbit.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.fluentbit.serviceAccount.annotations | indent 4 }}
  {{- end }}
  labels:
{{ include "smctf-observability.labels" . | indent 4 }}
{{- end }}
